### ISSUE TITLE
Download of cert fails if nodepki is running behind a reverse proxy

### ISSUE THREAD

**Issue by PhilipSchmid** [aditosoftware/nodepki-webclient#13]
Hi there,

If the nodepki service is running behind a reverse proxy (e.g. Traefik) which proxies e.g. `ca.example.com` to `nodepki:8080`, the download of the root / intermediate cert fails because of a wrong URL concatenation. The URL then points to http://ca.example.com:8080/public/ca/root/cert instead of http://ca.example.com/public/ca/root/cert where it should point to (note the missing `:8080`).

https://github.com/aditosoftware/nodepki-webclient/blob/a5f9aca05db9a204ed27ea11e9b0df723fe07b65/controllers/cacerts.js#L41

Any ideas how to fix this so both setups are able to provide a certificate download (with RP or without RP)?

Thanks.

Regards,
Philip

**Comment by jboesl** [comment]
I think the download should use the host name provided by the http headers in the field 'Host'. The port should be included there in case it's not the default port.
